"""Exercise the upload archive through its CLI, with real files and no mocks."""
import os
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "build_plugin_zip.py"


@pytest.fixture
def source(tmp_path):
    root = tmp_path / "source"
    shutil.copytree(REPO / "plugins", root / "plugins")
    shutil.copytree(REPO / ".claude-plugin", root / ".claude-plugin")
    (root / "private-notes.txt").write_text("do not ship")
    (root / "evals").mkdir()
    (root / "evals" / "fixture.txt").write_text("do not ship")
    return root


def build(root, output):
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--root", str(root), "--output", str(output)],
        capture_output=True, text=True,
    )


def test_archive_has_one_plugin_root_and_preserves_skill_files(source, tmp_path):
    # Bug caught: archiving the whole repository, omitting skills, or changing their bytes.
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 0, result.stdout + result.stderr
    with zipfile.ZipFile(output) as archive:
        names = archive.namelist()
        assert {name.split("/")[0] for name in names} == {"ionden-skills"}
        assert "ionden-skills/.codex-plugin/plugin.json" in names
        assert "ionden-skills/.claude-plugin/icon.svg" in names
        assert "ionden-skills/LICENSE" in names
        assert "ionden-skills/README.md" in names
        assert not any("marketplace.json" in name or "evals/" in name for name in names)
        for skill in ("subagent-optimizer", "skill-optimizer", "writing-tests-that-can-fail"):
            name = f"ionden-skills/skills/{skill}/SKILL.md"
            assert archive.read(name) == (source / "plugins" / name).read_bytes()
        assert archive.testzip() is None


def test_archive_bytes_do_not_depend_on_mtime_or_umask(source, tmp_path):
    # Bug caught: using ZIP defaults that embed file timestamps or caller permission bits.
    first, second = tmp_path / "first.zip", tmp_path / "second.zip"
    assert build(source, first).returncode == 0
    skill = source / "plugins/ionden-skills/skills/skill-optimizer/SKILL.md"
    os.utime(skill, (1750000000, 1750000000))
    skill.chmod(0o600)
    assert build(source, second).returncode == 0
    assert first.read_bytes() == second.read_bytes()


def test_archive_reflects_changed_skill_content(source, tmp_path):
    # Bug caught: reusing a cached archive after a skill changes.
    first, second = tmp_path / "first.zip", tmp_path / "second.zip"
    assert build(source, first).returncode == 0
    skill = source / "plugins/ionden-skills/skills/skill-optimizer/SKILL.md"
    with skill.open("a") as stream:
        stream.write("\nNew supporting instruction.\n")
    assert build(source, second).returncode == 0
    with zipfile.ZipFile(second) as archive:
        assert archive.read("ionden-skills/skills/skill-optimizer/SKILL.md").endswith(
            b"\nNew supporting instruction.\n"
        )
    assert first.read_bytes() != second.read_bytes()


def test_archive_excludes_caches_and_finder_files(source, tmp_path):
    # Bug caught: shipping locally generated bytecode or Finder state.
    scripts = source / "plugins/ionden-skills/skills/skill-optimizer/scripts"
    (scripts / "__pycache__").mkdir(exist_ok=True)
    (scripts / "__pycache__/stale.pyc").write_bytes(b"junk")
    (scripts / "stale.pyc").write_bytes(b"junk")
    (scripts / ".DS_Store").write_bytes(b"junk")
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 0, result.stdout + result.stderr
    with zipfile.ZipFile(output) as archive:
        assert not any("__pycache__" in name or name.endswith((".pyc", ".DS_Store"))
                       for name in archive.namelist())


@pytest.mark.parametrize("is_directory", [False, True])
def test_archive_rejects_symlinks_instead_of_copying_external_files(source, tmp_path, is_directory):
    # Bug caught: dereferencing a link and leaking files outside the plugin.
    external = tmp_path / "external"
    if is_directory:
        external.mkdir()
        (external / "private.txt").write_text("private")
    else:
        external.write_text("private")
    link = source / "plugins/ionden-skills/skills/skill-optimizer/references/external"
    link.symlink_to(external, target_is_directory=is_directory)
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 1
    assert "symlink" in result.stderr.lower()
    assert not output.exists()


def test_archive_rejects_unexpected_plugin_contents(source, tmp_path):
    # Bug caught: bypassing the packaging validator and including a live MCP configuration.
    (source / "plugins/ionden-skills/.mcp.json").write_text("{}")
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 1
    assert ".mcp.json" in result.stdout + result.stderr
    assert not output.exists()


def test_archive_rejects_missing_skills(source, tmp_path):
    # Bug caught: producing a valid-looking archive that imports zero skills.
    shutil.rmtree(source / "plugins/ionden-skills/skills")
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 1
    assert "no skills" in (result.stdout + result.stderr).lower()
    assert not output.exists()


def test_archive_does_not_overwrite_an_existing_file(source, tmp_path):
    # Bug caught: truncating the previous release instead of requiring a new output path.
    output = tmp_path / "upload.zip"
    output.write_bytes(b"previous release")
    result = build(source, output)
    assert result.returncode == 1
    assert output.read_bytes() == b"previous release"


def test_archive_cannot_be_created_inside_the_plugin(source):
    # Bug caught: including the output ZIP itself, or leaving a new stray inside the install tree.
    output = source / "plugins/ionden-skills/skills/skill-optimizer/scripts/upload.zip"
    result = build(source, output)
    assert result.returncode == 1
    assert "outside" in result.stderr.lower()
    assert not output.exists()


def test_archive_preserves_executable_scripts(source, tmp_path):
    # Bug caught: making bundled shell helpers non-executable after extraction.
    script = source / "plugins/ionden-skills/skills/subagent-optimizer/scripts/helper.sh"
    script.write_text("#!/bin/sh\nexit 0\n")
    script.chmod(0o755)
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 0, result.stdout + result.stderr
    with zipfile.ZipFile(output) as archive:
        mode = archive.getinfo("ionden-skills/skills/subagent-optimizer/scripts/helper.sh").external_attr >> 16
        assert mode & 0o111 == 0o111


def test_archive_rejects_hidden_supporting_files(source, tmp_path):
    # Bug caught: shipping a forgotten local .env underneath an allowed scripts folder.
    (source / "plugins/ionden-skills/skills/skill-optimizer/scripts/.env").write_text("private")
    output = tmp_path / "upload.zip"
    result = build(source, output)
    assert result.returncode == 1
    assert "hidden" in result.stderr.lower()
    assert not output.exists()
